// Generated by nuxi
/// <reference types="@nuxt/image" />
/// <reference types="shadcn-nuxt" />
/// <reference types="@nuxt/icon" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="@nuxt/ui" />
/// <reference path="types/builder-env.d.ts" />
/// <reference types="nuxt" />
/// <reference path="types/app-defaults.d.ts" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/build.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="types/ui.d.ts" />
/// <reference path="../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_@netlify+blobs@8.2.0_db0@0.3.2_embla-carousel@8.6.0_f6030f91e876b8c719e2dcde12f1695b/node_modules/@nuxt/ui/dist/runtime/types/app.config.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/nitro-middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
